scrape_configs:
  - job_name: 'OrderMetrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['35.247.111.123:80','host.docker.internal:80']
        labels:
          application: 'order'